title: David Yune
description: Student Athlete • Data + Biology • Portfolio & Blog
theme: minima
author: David Yune
email: dyune@wm.edu

# Shows pages in the top nav
header_pages:
  - index.md
  - resume.md
  - blog.md
  - about.md

# Makes URLs clean
permalink: /:categories/:year/:month/:day/:title/
